import { Col, Row } from "antd";
import { Item } from "../../components/Item";



const InfoArray = [
	{ id: 1, name: 'Задача 1', author: 1, workers: '1/1', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. ' },
	{ id: 2, name: 'Задача 2', author: 2, workers: '2/2', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 3, name: 'Задача 3', author: 3, workers: '3/3', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 4, name: 'Задача 4', author: 4, workers: '4/4', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 5, name: 'Задача 5', author: 5, workers: '5/5', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 6, name: 'Задача 6', author: 6, workers: '6/6', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 7, name: 'Задача 7', author: 7, workers: '7/7', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
	{ id: 8, name: 'Задача 8', author: 8, workers: '8/8', rating: '5.3', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. Duis tempor quam ac dapibus pellentesque. Duis metus eros, maximus et tempus condimentum, vulputate fringilla velit. Sed elementum risus in libero venenatis, non eleifend est congue. Etiam fermentum augue eget posuere tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce feugiat magna ipsum. Duis vel est tellus. Proin rutrum, ipsum a aliquam tempor, metus elit dictum sem, et feugiat nisl sapien eu mauris. Pellentesque et hendrerit diam, convallis fermentum risus. Quisque et elit pellentesque, lobortis nisl ac, aliquam ante. Praesent eu pulvinar tellus. Sed mi neque, imperdiet quis odio sed, convallis varius nibh. Donec sit amet egestas massa, et ultrices massa. '  },
]
export const Tasks = () => {
	return <div style={{ maxWidth: 1024 }}>
		<Row justify="center" gutter={[24, 24]}>
			{InfoArray.map((item) => {
				return (
					<Col style={{ display: 'flex', justifyContent: 'center' }} xs={16} sm={12} md={8} lg={6} xl={6} >
						<Item key={item.id} item={item} />
					</Col>
				);
			})}
		</Row>
	</div>;
};
